openapi: 3.0.0
info:
  title: Crowd Comic API
  description: Crowd Comic API docs
  version: 1.0.0
paths:
  /help:
    get:
      description: Fetch a list of valid endpoints
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/help'
          description: hi
components:
  schemas:
    help:
      type: object
      properties:
        /:
          type: string
        /help:
          type: string
        /createUser:
          type: string
        /changePassword:
          type: string
        /changeDisplayName:
          type: string
